# Overview {.unnumbered}

This book contains data analysis journeys to practice your wrangling, visualisation, and analysis skills in a less structured format than the main PsyTeachR books. We have designed these tasks as a bridge between the structured learning in the core course book chapters and your assessments. 

We present you with a new data set, show you what the end product should look like, and see if you can apply your data wrangling, visualisation, and/or analysis skills to get there. They apply across all levels and our PsyTeachR books, but your lecturer will point you to the most appropriate chapters for which skills you have developed. 

As you gain independence, this is the crucial skill. Data analysis is all about seeing the data you have available to you and identifying what the end product needs to be to apply your visualisation and analysis techniques. You can then mentally (or physically) create a checklist of tasks to work backwards to get there. There might be a lot of trial and error as you try one thing, it does not quite work, so you go back and try something else. If you get stuck though, we have a range of hints and task lists that you can unhide, then the solution to check your attempts against. 
